const
  hcAbout                = 1000,
  hcAdress               = 1001,
  hcCont                 = 1111,
  hcFilePath             = 1002,
  hcGenOpt               = 1010,
  hcQuit                 = 1004,
  hcScripts              = 1003,
  hcdomains              = 1012,
  hcindex                = 5555,
  hclogopt               = 1014,
  hcmeopt                = 1018,
  hcpaopt                = 1017,
  hcscropt               = 1016;
